Event file generator
JuPedSim/simulator pull request #27
Opened 2020-11-20 08:49 UTC by schroedtert

Simple event file generator to create one single pedestrian at a given time on a position on a specific floor:
```bash
jps generate-pedestrians -x 1 -y 10 -o events.json
```

- [ x ] Single pedestrian at a specific position
- [ ] Single pedestrian inside a area (bounding box from command line)
- [ ] Single pedestrian inside a area (from `world.dxf`)
- [ ] Multiple pedestrians  inside a area (bounding box from command line)
- [ ] Multiple pedestrians  inside a area (from `world.dxf`)

2020-12-14 15:48 UTC, schroedtert commented
This should now be ready for the first round of reviews. Please have a close look at the tests and if I have any cases.
Also we should add the reporting of the pytests to the CI such that they are visible (@zeroset)

2021-01-18 21:35 UTC, JetteSchumann requested changes

2021-01-18 21:35 UTC, JetteSchumann commented on jps/jupedsim/tests/util/test_event.py
> +                '{"type": "spawn_pedestrian", "position": [0, 0], "floor": 1, "test": [0, 0]}',
"test" is ignored, isn't it?

2021-01-18 21:35 UTC, JetteSchumann commented on jps/jupedsim/util/event.py
> +        if time < 0.0:
We should check if the precision of "time" is higher than the actual simulation time steps at some point (later?). We could just print a warning I guess

2021-01-18 21:35 UTC, JetteSchumann commented on jps/jupedsim/tests/util/test_event.py
> +                Event(0.5, SpawnPedestrianEvent([0.25, 0], 6)).get_json(),
What about high time precision? e.g. 0.5555555555

2021-01-18 21:35 UTC, JetteSchumann commented on jps/jupedsim/tests/util/test_generator.py
> +                Event(123, SpawnPedestrianEvent([21, -5], 1)),
you should add a floating point example for time

2021-01-18 21:35 UTC, JetteSchumann commented on jps/jupedsim/tests/util/test_generator.py
> +        foo = SpawnPedestrianEvent([0, 0], 1)
`foo` ist not used

2021-01-18 21:35 UTC, JetteSchumann commented on jps/jupedsim/tests/util/test_generator.py
> +            file = tmpdir / filename
Where is `tmpdir` defined?

2021-01-18 21:35 UTC, JetteSchumann commented on jps/jupedsim/tests/util/test_generator.py
> +            Event(56123, SpawnPedestrianEvent([12, 85], 4)),
Maybe add some floating point examples

2021-01-18 21:35 UTC, JetteSchumann commented on jps/jupedsim/tests/util/test_generator.py
> +                ],
Does this mean: generate-pedestrians with no generated output is the same as removing spawn events from the old file?

2021-01-18 21:35 UTC, JetteSchumann commented on jps/jupedsim/tests/util/test_generator.py
> +                    Event(123, SpawnPedestrianEvent([21, -5], 1)),
Actually, this should not be possible? Same pos at same time... Or do we take care of this at another point?

2021-01-18 21:35 UTC, JetteSchumann commented on jps/jupedsim/tests/util/test_generator.py
> +                    Event(512, SpawnPedestrianEvent([8, -45], 1)),
you should add a test where the new and old events are exactly the same. Do they appear twice in the result?

2021-01-19 09:34 UTC, JetteSchumann commented on jps/jupedsim/util/generator.py
> +    return merged_events
Actually, I assumed that the overwrite option refers to the entire file. But enabling for EventTypes makes sense when we want to change only one event type and repeat the simulation with the other remaining settings in the future.

2021-01-25 18:43 UTC, schroedtert commented on jps/jupedsim/tests/util/conftest.py
> +    return not unmatched
Add comments

2021-01-25 18:43 UTC, schroedtert commented on jps/jupedsim/tests/util/test_generator.py
> +                ],
Not exactly, as `generate-pedestrians` can't be called without time and coordinate. But if we would enable such option it could be use in that way.

2021-01-25 18:43 UTC, schroedtert commented on jps/jupedsim/tests/util/test_generator.py
> +                    Event(123, SpawnPedestrianEvent([21, -5], 1)),
We need to decide this. But from my understanding this type of conflict solving needs to be included anyway (positions too close, pedestrian walking at spawning point, ...)

2021-01-25 18:43 UTC, schroedtert commented on jps/jupedsim/tests/util/test_generator.py
> +                    Event(512, SpawnPedestrianEvent([8, -45], 1)),
Currently they appear twice. From my understanding this is the expected behavior as the existing events should not be overwritten. Added the test cases.

2021-01-25 18:43 UTC, schroedtert commented on jps/jupedsim/util/event.py
> +        return json.dumps(self, default=lambda o: o.__dict__)
As the EventType is not directly serializable this step is needed to convert the dataclass to a dict, which then can be dumped by json.

2021-01-25 18:43 UTC, schroedtert commented on jps/jupedsim/util/event.py
> +        event_type = json.dumps(event_type_json)
It is needed to not have to different parsers, one for json and one for a dict, returned by `json_data.get("event")`. Not sure if this is a best way, though.

2021-01-25 18:43 UTC, schroedtert commented on jps/jupedsim/util/generator.py
> +def process_generator(args) -> None:
Yes it is, changed it.

2021-01-25 18:43 UTC, schroedtert commented on jps/jupedsim/util/generator.py
> +    if len(args.x) == 1 and len(args.y) == 1 and args.floor is not None:
Not needed anymore, should be handled by the creation of the events (input check)

2021-01-25 18:43 UTC, schroedtert commented on jps/jupedsim/util/generator.py
> +    return merged_events
Maybe this function can be extended to delete a certain event type. When this is possible it might make sense to make sense to keep it as an extra tool, as `jps delete-event-type spawn_pedestrian events.json`

2021-01-25 18:43 UTC, schroedtert commented on jps/jupedsim/util/generator.py
> +    events = []
Improved comment

2021-01-25 18:43 UTC, schroedtert commented on jps/jupedsim/util/event.py
> +        if time < 0.0:
Yes, that would make sense. But we have to see how the precision can be forwarded here.

2021-01-25 18:44 UTC, schroedtert commented on jps/jupedsim/application.py
> +            help="Time the pedestrian(s) should be generated",
Yes, added the information to the comment

2021-02-02 11:38 UTC, JetteSchumann submitted a review, later dismissed

2021-02-02 11:38 UTC, JetteSchumann commented on jps/jupedsim/application.py
>          parser = self.subparsers.add_parser(
We should discuss that in future when we the definition of (spawning) special areas and their properties are clearer

2021-02-02 11:38 UTC, JetteSchumann commented on jps/jupedsim/tests/util/test_event.py
> +                Event(0.5, SpawnPedestrianEvent([0.25, 0], 6)).get_json(),
not sure anymore. Think it was related to the time precision of input (given precision) and the simulation (possible precision)

2021-02-03 10:06 UTC, JetteSchumann approved these changes

2021-02-03 10:07 UTC, merged