Adds the clang format configuration
JuPedSim/simulator pull request #3
Opened 2020-10-17 17:50 UTC by zeroset

Any comment on the old clang format config? We could change it easily now ;)

2020-10-17 19:10 UTC, Ozaq requested changes
Have a look at the language standard,

2020-10-17 19:10 UTC, Ozaq commented on .clang-format
> +Standard: Cpp11
This should be Cpp17 probably. Also it looks like the flag is incorrect even for c++11.
I think it should be ˋc++17ˋ. See https://releases.llvm.org/10.0.0/tools/clang/docs/ClangFormatStyleOptions.html

2020-10-20 07:49 UTC, schroedtert commented on .clang-format
> +AccessModifierOffset: '-4'
I get a warning here from my IDE:
> Schema validation: Incompatible types. Required: integer. Actual: string. 
> AccessModifierOffset: integer
Same for all integer and boolean values below.

2020-10-20 07:50 UTC, schroedtert commented on .clang-format
> +Standard: Cpp11
Changed

2020-10-20 09:41 UTC, zeroset commented on .clang-format
> +AccessModifierOffset: '-4'
Fixed it, could you please recheck it?

2020-10-20 12:02 UTC, schroedtert commented on .clang-format
> +AllowShortBlocksOnASingleLine: true
From the documentation: https://releases.llvm.org/10.0.0/tools/clang/docs/ClangFormatStyleOptions.html#AllowShortBlocksOnASingleLine
This can either be `never`, `empty`, or `always`

2020-10-20 12:02 UTC, schroedtert commented on .clang-format
> +
Do we need this empty line?

2020-10-20 12:16 UTC, zeroset commented on .clang-format
> +AlignTrailingComments: 'true'
done

2020-10-20 12:16 UTC, zeroset commented on .clang-format
> +AllowShortBlocksOnASingleLine: true
done

2020-10-20 12:16 UTC, zeroset commented on .clang-format
> +
removed

2020-10-20 12:37 UTC, Ozaq approved these changes

2020-10-20 12:37 UTC, merged