LengthUnit implementation
JuPedSim/simulator pull request #38
Opened 2020-12-18 08:32 UTC by zeroset

`LengthUnit` provides a strong type for all length units.  It stores the actual unit using int64 in the defined `RESOLUTION` (currently micro meter). It automatically scales the unit to mum and to the desired unit in the `get` method. 
We store the quantity in a single resolution unit to avoid a lot of scaling for arithmetic operations. Additionally we decided that micro meter should be enough for all use cases in the simulator. 
Arithmetic operations are following.

2020-12-27 22:43 UTC, Ozaq commented on cpp/libcore/source/geometry/length_unit.hpp
> +    LengthUnitParams(LengthUnitParams && p_other) noexcept = default;
Having a move operator on this type does not make a lot of sense imo since the type just wraps `QuantityType`. Support for copy seems to be the more natural choice. Esp looking at the code I can see no use of copy and/or move either.

2020-12-27 22:43 UTC, Ozaq commented on cpp/libcore/source/geometry/length_unit.hpp
> +    bool operator==(QuantityType p_other) const { return m_quantity == p_other; }
This looks wrong: a comparison operator taking a different type

2020-12-27 22:43 UTC, Ozaq commented on cpp/libcore/test/.clang-tidy
> +  -cppcoreguidelines-avoid-magic-numbers
The old code was riddled with magic numbers. I think this is a very good check to keep.
Edit: Both checks

2020-12-27 22:43 UTC, Ozaq commented on cpp/libcore/test/geometry/test_length_unit.cpp
> +
tests for `operator==` are missing

2020-12-27 22:46 UTC, Ozaq commented
Adding user defined string literals would make using this new type a lot more ergonomic imo: 

```cpp
LengthUnit operator"" _um(unsigned long long p_quantity)
{
    return makeLengthUnit<Units::mum>(p_quantity);
}

LengthUnit operator"" _mm(unsigned long long p_quantity)
{
    return makeLengthUnit<Units::mm>(p_quantity);
}

LengthUnit operator"" _cm(unsigned long long p_quantity)
{
    return makeLengthUnit<Units::cm>(p_quantity);
}

LengthUnit operator"" _dm(unsigned long long p_quantity)
{
    return makeLengthUnit<Units::dm>(p_quantity);
}

LengthUnit operator"" _m(unsigned long long p_quantity)
{
    return makeLengthUnit<Units::m>(p_quantity);
}

LengthUnit operator"" _km(unsigned long long p_quantity)
{
    return makeLengthUnit<Units::km>(p_quantity);
}
```

With this you can do that:

```
const auto len_1 = 10_m;
// instead off
const auto len_2 = makeLengthUnit<Units::m>(10);
``

2020-12-27 22:48 UTC, Ozaq commented on cpp/libcore/source/geometry/length_unit.hpp
> +enum class Units { mum = -6, mm = -3, cm = -2, dm = -1, m = 0, km = 3 };
`mum` for micro meters seems to be a bit unusal choice. So far I have always encountered `um` for micro meters. I think to be as close to `µm` as possible.

2021-01-04 11:18 UTC, zeroset commented on cpp/libcore/source/geometry/length_unit.hpp
> +    bool operator==(QuantityType p_other) const { return m_quantity == p_other; }
I have no idea what i did here! :D Especially we do not want to compare integrals without units. I deleted it.

2021-01-04 11:21 UTC, zeroset commented on cpp/libcore/source/geometry/length_unit.hpp
> +    LengthUnitParams(LengthUnitParams && p_other) noexcept = default;
`LengthUnitParams` should be used as temporary only type. I wanted to avoid that someone is creating this type and stores it to a variable... Especially i dont want the values be copied all the time. Do you think it is bad practice to have it move only? Or misleading?

2021-01-04 11:23 UTC, zeroset commented on cpp/libcore/source/geometry/length_unit.hpp
> +        return p_quantity * jps::math::intPow<T, DECIMAL_BASE, diff_exp>();
I was afraid that overflow checks would be to expensiv, since this is used in a getter of the length unit. But we distinguish between `exp < 0` anyways. So for positive exponent we could introduce overflow check. The length unit stores the quantity in micro meter anyways. So most often the overflow check would not be triggered.

2021-01-04 11:23 UTC, zeroset commented on cpp/libcore/test/.clang-tidy
> +  -cppcoreguidelines-avoid-magic-numbers
This is just the clang tidy config for the unittests. The "normal" config has the tests still enabled.

2021-01-04 11:24 UTC, zeroset commented on cpp/libcore/source/geometry/length_unit.hpp
> +enum class Units { mum = -6, mm = -3, cm = -2, dm = -1, m = 0, km = 3 };
You are right. renamed it.

2021-01-26 11:16 UTC, schroedtert requested changes
As discussed before: `operator==` and comparison operators (<,>) are missing plus tests.

2021-01-26 11:16 UTC, schroedtert commented on cpp/libcore/source/CMakeLists.txt
> +    geometry/length_unit.hpp
Should this become part of geometry or rather util? Not sure if it might get used outside of geometry.

2021-01-27 07:52 UTC, zeroset commented
Implemented the Comparisons

2021-01-27 07:53 UTC, zeroset commented on cpp/libcore/source/geometry/length_unit.hpp
> +        return p_quantity * jps::math::intPow<T, DECIMAL_BASE, diff_exp>();
We changed the quantity to double out of different reasons.

2021-01-27 07:54 UTC, zeroset commented on cpp/libcore/source/geometry/length_unit.hpp
> +    LengthUnitParams(LengthUnitParams && p_other) noexcept = default;
You are right. Was somehow premature optimization. Removed all deleted and defaulted Constructors. The Compiler will do his job here.

2021-01-27 07:55 UTC, zeroset commented on cpp/libcore/test/geometry/test_length_unit.cpp
> +
I added correct comparison operators (removed the one comparing with a different type). Also added tests for them.

2021-01-28 12:58 UTC, schroedtert approved these changes

2021-01-28 12:58 UTC, schroedtert commented on cpp/libcore/source/geometry/length_unit.hpp
> +        "scaleQuantity should be used with floating point types only.");
Will be added separately

2021-01-28 12:59 UTC, schroedtert commented on cpp/libcore/source/CMakeLists.txt
> +    geometry/length_unit.hpp
After discussion: LengthUnit remains part of geometry

2021-01-28 14:17 UTC, merged