Add basic cpp setup
JuPedSim/simulator pull request #4
Opened 2020-10-17 23:09 UTC by Ozaq

Dependecies setup via setup-dependencies.sh
Initially contains:
	googletest 1.10.0
	pybind11 2.5.0

Usage: ./setup-dependencies.sh <location>

Example library added with unit test, python binding and python test
that actually calls imports and executes the example python binding.

All tests are available via ctest.

2020-10-18 11:46 UTC, schroedtert commented on cpp/CMakeLists.txt
> +include(GoogleTest)
This will later only be included when the tests are build, right? Like now with the `BUILD_TEST` option?

2020-10-18 14:52 UTC, Ozaq commented on cpp/CMakeLists.txt
> +include(GoogleTest)
So far we didn’t discuss if we expect users to build from source or if we only expect to build with tests. So I did opt to not add any configuration possibility for now. This is something we can add on later however if we work on providing a pip package. In that case we would not build tests during pip install.

2020-10-19 13:23 UTC, zeroset requested changes

2020-10-19 13:23 UTC, zeroset commented on cpp/scripts/setup-dependencies.sh
> +set -ex
I would love to have a short comment with documentation about what the script is doing.

2020-10-19 20:44 UTC, Ozaq commented on cpp/scripts/setup-dependencies.sh
> +set -ex
I have added a Readme to the folder, this way the doc will show up in Github. I think this might be a bit easier than doc inside the script itself.

2020-10-19 21:23 UTC, zeroset approved these changes
Thanks!

2020-10-20 07:43 UTC, merged