Extend functionality of basic spatial data types
JuPedSim/simulator pull request #43
Opened 2021-02-15 16:12 UTC by schroedtert

Added some basic features for basic data types:
- copy constructor, copy assignment operator
- move constructor, move assignment operator
- equal, unequal operator
- convenience getters
- tests for the operations
- add formatting for fmt

2021-02-15 16:14 UTC, schroedtert commented on cpp/libcore/source/geometry/line_segment.hpp
> +    }
Are roated line segments (start and end switched) equal?

2021-02-15 16:14 UTC, schroedtert commented on cpp/libcore/source/geometry/special_area.hpp
> +    }
Is testing the equality of the ID sufficient?

2021-02-18 14:45 UTC, zeroset requested changes
Please remove empty file `cpp/libcore/source/geometry/world_builder.cpp` 
I did not read the tests yet.

2021-02-18 14:45 UTC, zeroset commented on cpp/libcore/source/geometry/line_segment.cpp
> +auto jps::LineSegment::rotate() -> void
This method is not used. Maybe we should write something like a view on line segment switching the getters without actually rotating the linesegment.

2021-02-18 14:45 UTC, zeroset commented on cpp/libcore/source/geometry/line_segment.hpp
> +    }
I would say yes. I think a lineSegment has no direction.

2021-02-18 14:45 UTC, zeroset commented on cpp/libcore/source/geometry/spatial_vector.hpp
> +    auto x() -> LengthUnit & { return m_x; }
Why a non-const reference here?

2021-02-18 14:45 UTC, zeroset commented on cpp/libcore/source/geometry/special_area.hpp
> +    }
No, i think we need to distinguish between external ID (color code) and internal ID (inherited from Identifiable). `m_id` should be renamed to `m_external_id` and the `Identifiable` class should be inherited. Comparing the internal ID should be sufficient.

2021-02-19 08:28 UTC, schroedtert commented on cpp/libcore/source/geometry/coordinate.hpp
> +    auto x() -> LengthUnit & { return m_x; }
Thought it might be a more intuitive interface for accessing the data members. But we could also make `m_x`, `m_y` and `m_lvl` publicly accessible.  
Just writing:
```cpp
coordinate.x() = new_x;
print("x={}", coordinate.x();
```
instead of
```cpp
coordinate.setX(new_x);
print("x={}", coordinate.getX();
```

2021-02-19 08:35 UTC, schroedtert commented on cpp/libcore/source/geometry/coordinate.hpp
> +    auto x() -> LengthUnit & { return m_x; }
Note: Using reference also complicates the pybindings ...

2021-02-22 16:42 UTC, schroedtert commented on cpp/libcore/source/geometry/spatial_vector.hpp
> +    auto x() -> LengthUnit & { return m_x; }
Changed it. Now public member.

2021-02-22 16:42 UTC, schroedtert commented on cpp/libcore/source/geometry/line_segment.cpp
> +auto jps::LineSegment::rotate() -> void
Still valid, or should we leave it as it is?

2021-02-22 16:42 UTC, schroedtert commented on cpp/libcore/source/geometry/coordinate.hpp
> +    auto x() -> LengthUnit & { return m_x; }
After discussion: `SpatialVector` and `Coordinate` are structs with public members.

2021-02-22 16:42 UTC, schroedtert commented on cpp/libcore/source/geometry/area.hpp
> +    Area(Area const & p_other) = default;
Delete all default definitions.

2021-02-22 16:42 UTC, schroedtert commented on cpp/libcore/source/geometry/area.hpp
> +    auto format(const jps::Area & p_area, FormatContext & p_ctx)
Changed to east const.

2021-02-22 16:42 UTC, schroedtert commented on cpp/libcore/source/geometry/area.hpp
> +    Area(std::vector<LineSegment> p_area_boundaries);
Changed.

2021-02-22 16:42 UTC, schroedtert commented on cpp/libcore/source/geometry/area.hpp
> +    Area(std::vector<Coordinate> p_area_polygon);
Changed.

2021-02-22 16:42 UTC, schroedtert commented on cpp/libcore/source/geometry/area.cpp
> +jps::Area::Area(std::vector<LineSegment> p_area_boundaries)
Changed it.

2021-02-22 16:42 UTC, schroedtert commented on cpp/libcore/source/geometry/area.cpp
> +    // TODO need to check of area of polygon == 0 (not a valid polygon)
Updated. Should be a reminder, that a proper test for valid polygons needs to be added, when we decide for a geometry library.

2021-02-22 16:43 UTC, schroedtert commented on cpp/libcore/source/geometry/special_area.hpp
> +    }
After discussion: Deleted == operator for `SpecialArea` as is does not seem to be necessary, as it is impossible that multiple equal `SpecialArea` exist.

2021-02-22 16:43 UTC, schroedtert commented on cpp/libcore/source/geometry/line_segment.hpp
> +    }
Agree, changed it.

2021-02-22 16:46 UTC, schroedtert commented on cpp/libcore/source/geometry/spatial_vector.hpp
> +    LengthUnit m_y; // NOLINTLINE
Should we stay with the `m_` prefix for public member?

2021-02-22 16:46 UTC, schroedtert commented on cpp/libcore/source/geometry/coordinate.hpp
> +    Level m_lvl;    // NOLINTLINE
Should we stay with the `m_` prefix for public member?

2021-02-22 17:48 UTC, zeroset commented on cpp/libcore/source/geometry/area.cpp
> +    // TODO need to check of area of polygon == 0 (not a valid polygon)
Can you create an issue and add all missing todos as a checkbox?

2021-02-22 17:51 UTC, zeroset commented on cpp/libcore/source/geometry/area.hpp
> +    auto format(const jps::Area & p_area, FormatContext & p_ctx)
We need a clang tidy check :D

2021-02-22 17:52 UTC, zeroset commented on cpp/libcore/source/geometry/line_segment.cpp
> +auto jps::LineSegment::rotate() -> void
Its ok, i tricked myself by folding the other code ;)

2021-02-22 17:54 UTC, zeroset commented on cpp/libcore/source/geometry/spatial_vector.hpp
> +    LengthUnit m_y; // NOLINTLINE
I think we set the prefix for private and protected member only and public should go lower_case without prefix?! I am open for discussion ;)

2021-02-23 11:07 UTC, schroedtert commented on cpp/libcore/source/geometry/spatial_vector.hpp
> +    LengthUnit m_y; // NOLINTLINE
Removed the prefixes

2021-02-23 11:07 UTC, schroedtert commented on cpp/libcore/source/geometry/coordinate.hpp
> +    Level m_lvl;    // NOLINTLINE
Removed the prefixes

2021-02-23 16:45 UTC, zeroset approved these changes

2021-02-23 16:45 UTC, zeroset commented on cpp/libcore/source/geometry/helper.cpp
> +#include "helper.hpp"
Maybe we should have a subfolder helper with different functions in different files? Or grouped helper files like polygon_helper...

2021-02-23 16:45 UTC, zeroset commented on cpp/libcore/source/geometry/line_segment.cpp
> +    auto tmp = m_start;
`std::swap(m_start, m_end)`

2021-02-23 16:45 UTC, zeroset commented on cpp/libcore/source/geometry/spatial_vector.hpp
> +public:
not necessary anymore.

2021-02-23 16:45 UTC, zeroset commented on cpp/libcore/source/geometry/coordinate.hpp
> +public:
Not necessary anymore.

2021-02-23 16:45 UTC, zeroset commented on cpp/libcore/source/geometry/coordinate.hpp
> +    LengthUnit y; // NOLINTLINE
Which check is failing here? Maybe just deactivate the specific test. Should we rethink the public var approach?

2021-02-24 11:21 UTC, schroedtert commented on cpp/libcore/source/geometry/helper.cpp
> +#include "helper.hpp"
Moved to `geometry/helper/polygon_helper.hpp/cpp`

2021-02-24 11:22 UTC, schroedtert commented on cpp/libcore/source/geometry/line_segment.cpp
> +    auto tmp = m_start;
Changed, could have thought this myself :D

2021-02-24 11:22 UTC, schroedtert commented on cpp/libcore/source/geometry/spatial_vector.hpp
> +public:
removed

2021-02-24 11:22 UTC, schroedtert commented on cpp/libcore/source/geometry/coordinate.hpp
> +public:
removed

2021-02-24 11:22 UTC, schroedtert commented on cpp/libcore/source/geometry/coordinate.hpp
> +    LengthUnit y; // NOLINTLINE
Now explicitly stating failing check: `cppcoreguidelines-non-private-member-variables-in-classes`

2021-02-24 14:07 UTC, zeroset approved these changes

2021-02-24 14:07 UTC, zeroset commented on cpp/libcore/source/CMakeLists.txt
> +        geometry/helper/polygon_helper.hpp
Indent please :)

2021-02-24 15:13 UTC, schroedtert commented on cpp/libcore/source/CMakeLists.txt
> +        geometry/helper/polygon_helper.hpp
Argh .. changed it

2021-02-24 15:19 UTC, zeroset approved these changes

2021-02-24 15:34 UTC, merged