Bindings for spatial data types
JuPedSim/simulator pull request #44
Opened 2021-02-18 09:00 UTC by schroedtert

Creates the binding for the spatial data types:
- Adds python bindings for basic spatial data types: All functions (as well as some convenience functions) are exposed to python
- Adds tests for the exposed functions

Note: Only simplified bindings for `LengthUnit`! 

Blocked by #43

2021-02-26 19:40 UTC, JetteSchumann requested changes
We should discuss how we handle pybinds in general.. for each available method? Or restricted for the python side? I don't think that we need to make every functionality of the geometry classes available for python - but it might be good to have them for exception handling, logging, ... I don't know yet.

@schroedtert Some tests are missing. The '__str__' and '__repr__' are not tested. Maybe this can be done with a string compare?

2021-02-26 19:40 UTC, JetteSchumann commented on cpp/pycore/test/geometry/line_segment_test.py
> +    def test_constructor(self, start, end):
You have missed testing this: `.def(pybind11::init<jps::LineSegment const &>())`.
It's done in test_rotate but should be separated. Also for failing..

2021-02-26 19:40 UTC, JetteSchumann commented on cpp/pycore/test/geometry/line_segment_test.py
> +    def test_constructor_failing(self, start, end):
You could add tests with invalid types here such as LineSegment(LengthUnit(0.1), LengthUnit(0.65))

2021-02-26 19:40 UTC, JetteSchumann commented on cpp/pycore/test/geometry/coordinate_test.py
> +    def test_constructor(self, x, y, lvl):
`def test_constructor_failing` is missing

2021-02-26 19:40 UTC, JetteSchumann commented on cpp/pycore/test/geometry/line_segment_test.py
> +class TestLineSegment:
You could add a test for read only property of start/end. Should be an OperationalError when attempting to write I think.

2021-02-26 19:40 UTC, JetteSchumann commented on cpp/pycore/test/geometry/spatial_vector_test.py
> +    def test_constructor(self, x, y):
`def test_constructor_failing` is missing

2021-02-26 19:40 UTC, JetteSchumann commented on cpp/pycore/test/geometry/special_area_test.py
> +    def test_constructor_from_coordinates(self, external_id, area):
naming: from coordinates?

2021-02-26 19:40 UTC, JetteSchumann commented on cpp/pycore/test/geometry/special_area_test.py
> +    def test_constructor_from_coordinates(self, external_id, area):
`def test_constructor_failing` is missing

2021-02-26 19:40 UTC, JetteSchumann commented on cpp/pycore/test/geometry/special_area_test.py
> +class TestSpecialArea:
read only property could be tested

2021-02-26 19:40 UTC, JetteSchumann commented on cpp/pycore/source/geometry/special_area_binding.cpp
> +}
Re the operators == and != available via the area binding? could be tested..

2021-02-26 19:40 UTC, JetteSchumann commented on cpp/pycore/test/geometry/area_test.py
> +    def test_constructor_from_coordinates_failing(self, coordinates):
Failing could be tested for other types as well
e.g.:  Area(LenghtUnit())

And what happens for invalid areas? (polygon not closed)

2021-02-26 19:40 UTC, JetteSchumann commented on cpp/pycore/test/geometry/area_test.py
> +                Coordinate(LengthUnit(7.11), LengthUnit(45.1), Level(3)),
Why do you create LineSegments from Coordinates instead of defining them here right away?

2021-02-26 19:40 UTC, JetteSchumann commented on cpp/pycore/test/geometry/area_test.py
> +class TestArea:
read only property could be tested

2021-03-01 14:34 UTC, schroedtert commented on cpp/pycore/test/geometry/area_test.py
> +    def test_constructor_from_coordinates_failing(self, coordinates):
> Failing could be tested for other types as well
e.g.: Area(LenghtUnit())

Using incompatible results in `TypeError`. But from my point of view, this would be testing python/pybind and not our implementation.

Example error output:
```
>       Area(LengthUnit(5))
E       TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
E           1. jpscore.geometry.Area(arg0: List[jps::Coordinate])
E           2. jpscore.geometry.Area(arg0: List[jps::LineSegment])
E       
E       Invoked with: 5.000 m
```

> And what happens for invalid areas? (polygon not closed)

At the moment closed and not closed polygons are allowed. We defined, that the last element and first element are the same, right? Then we should fix it in an other issue.

2021-03-01 14:34 UTC, schroedtert commented on cpp/pycore/test/geometry/area_test.py
> +                Coordinate(LengthUnit(7.11), LengthUnit(45.1), Level(3)),
Thought it is easier that way. But defining the `line_segments` makes more sense, and the coordinates can get extracted from there, too.

2021-03-01 14:34 UTC, schroedtert commented on cpp/pycore/test/geometry/coordinate_test.py
> +    def test_constructor(self, x, y, lvl):
See above.

2021-03-01 14:34 UTC, schroedtert commented on cpp/pycore/test/geometry/line_segment_test.py
> +class TestLineSegment:
Added the test.

2021-03-01 14:34 UTC, schroedtert commented on cpp/pycore/test/geometry/line_segment_test.py
> +    def test_constructor(self, start, end):
Was a workaround. Delete the constructor.

2021-03-01 14:34 UTC, schroedtert commented on cpp/pycore/test/geometry/line_segment_test.py
> +    def test_constructor_failing(self, start, end):
See above

2021-03-01 14:34 UTC, schroedtert commented on cpp/pycore/test/geometry/spatial_vector_test.py
> +    def test_constructor(self, x, y):
See above

2021-03-01 14:34 UTC, schroedtert commented on cpp/pycore/test/geometry/special_area_test.py
> +class TestSpecialArea:
changed

2021-03-01 14:35 UTC, schroedtert commented on cpp/pycore/source/geometry/area_binding.cpp
> +        });
I think is it needed to distinguish between the two in our case. Maybe `__str__`  is a little bit too detailed.
@zeroset what is your opinion?

2021-03-02 18:14 UTC, zeroset commented on cpp/pycore/source/geometry/area_binding.cpp
> +        });
Actually i like the different meaning of `__repor__` and `__str__`, nevertheless i  am not sure if it is worth to implement different formatting. But maybe we need different accuracy in the output anyways. Can we define our own accuracy parameter in libfmt?

2021-03-05 07:56 UTC, JetteSchumann commented on cpp/pycore/source/geometry/area_binding.cpp
> +        .def_property_readonly("polygon", &jps::Area::getPolygon)
True. Was just thinking about consistent naming conventions. But I think it's not important here.

2021-03-05 07:57 UTC, JetteSchumann commented on cpp/pycore/source/geometry/area_binding.cpp
> +        });
will be solved with #52

2021-03-05 08:23 UTC, JetteSchumann submitted a review, later dismissed
Looks good now.

For me it's still difficult to clearly separate tests for pybinds and for their actual functionality. Such as for `rotate` for `LineSegment`. We need to ensure that the pybind is available and somehow working.. But the actual functionality should only be tested on c++ side. Otherwise it's tested twice.
We should discuss how to handle this for more complex functions in future.

2021-03-05 08:57 UTC, JetteSchumann commented on cpp/pycore/test/geometry/area_test.py
> +    def test_constructor_from_coordinates_failing(self, coordinates):
new issue #53

2021-03-05 12:31 UTC, JetteSchumann approved these changes

2021-03-05 12:34 UTC, merged