Length unit binding
JuPedSim/simulator pull request #50
Opened 2021-02-26 14:24 UTC by zeroset

Bindings for the constructor and the read only properties. 
The constructor requires two arguments. The quantity and the unit of this quantity. Unfortunately we need a big switch statement which is matching the unit with a literal of the same unit to select the correct template function. Can be called in python like: 
``` py
lu = LengthUnit(5.0, Units.mm)
```
The read only property call the getter of the length unit to retrieve the quantity in the desired unit. Can be called like: 
``` py
print(lu.um)
```
Unfortunately a lot of copy and paste since templated functions can not be set by dynmic variables. 

Attention the PR is based on #44 and will be based onto main after merge of #44.

2021-03-08 17:49 UTC, schroedtert requested changes

2021-03-08 17:49 UTC, schroedtert commented on cpp/pycore/source/geometry/length_unit_binding.cpp
> +                break;
Are this and the following `break`s needed?

2021-03-08 17:49 UTC, schroedtert commented on cpp/pycore/source/geometry/length_unit_binding.cpp
> +                    FMT_STRING("Unit ({}) not yet implemented in python bindings."), unit));
This part is not tested yet or am I missing something?

2021-03-08 17:49 UTC, schroedtert commented on cpp/pycore/source/geometry/length_unit_binding.cpp
> +    lu_binding.def(pybind11::init([](jps::LengthUnit::QuantityType quantity, jps::Units unit) {
you used a different sty;e for the binding all others wrote:
```cpp
binding.def(...)
    .def(...)
    .def(...)
```

2021-03-08 17:49 UTC, schroedtert commented on cpp/pycore/source/geometry/length_unit_binding.cpp
>          .export_values();
Is there a possibility to check whether all elements of the enum are exported? Just to ensure that one will not forget any future LengthUnit here

2021-03-16 16:50 UTC, zeroset commented on cpp/pycore/source/geometry/length_unit_binding.cpp
> +                break;
I think they are not needed, but i would prefer having them anyways. Otherwise i would be afraid someone changes the returns and forgets to add breaks.

2021-03-16 16:53 UTC, zeroset commented on cpp/pycore/source/geometry/length_unit_binding.cpp
> +                    FMT_STRING("Unit ({}) not yet implemented in python bindings."), unit));
The Problem is, i used all values of the enumeration in the above switch statement. For Testing i would need a new unit which is defined in the enumeration but not in the switch. The default case only triggers if someone adds a new unit and forgets the binding. I have no idea how to check this, nevertheless i think it is a valid point to have the default there...

2021-03-16 16:58 UTC, zeroset commented on cpp/pycore/source/geometry/length_unit_binding.cpp
>          .export_values();
No. Enums in C++ without reflections are not really powerful for those purposes. We could write our own enum type, but at the moment i would prefer to keep it like this until we have reflections or a better idea ;)

2021-03-16 17:00 UTC, zeroset commented on cpp/pycore/source/geometry/length_unit_binding.cpp
> +    lu_binding.def(pybind11::init([](jps::LengthUnit::QuantityType quantity, jps::Units unit) {
I tried to define the bindings in a for loop. After i failed a kept the binding like this. I think it is ok to have two variants?

2021-03-17 08:16 UTC, schroedtert commented on cpp/pycore/source/geometry/length_unit_binding.cpp
> +                break;
There is a compiler warning for this case `-Wimplicit-fallthrough`, not sure if we use it currently.

2021-03-17 08:19 UTC, schroedtert commented on cpp/pycore/source/geometry/length_unit_binding.cpp
> +    lu_binding.def(pybind11::init([](jps::LengthUnit::QuantityType quantity, jps::Units unit) {
In the other classes we defined the classes like:
```cpp
   pybind11::class_<jps::LengthUnit>(m, "LengthUnit")
    // Constructor switching the unit to the corresponding template parameter
    .def(pybind11::init([](jps::LengthUnit::QuantityType quantity, jps::Units unit) {
        switch(unit) {
            case jps::Units::um:
                return jps::makeLengthUnit<jps::Units::um>(quantity);
                break;
            case jps::Units::mm:
                return jps::makeLengthUnit<jps::Units::mm>(quantity);
                break;
            case jps::Units::cm:
                return jps::makeLengthUnit<jps::Units::cm>(quantity);
                break;
            case jps::Units::dm:
                return jps::makeLengthUnit<jps::Units::dm>(quantity);
                break;
            case jps::Units::m:
                return jps::makeLengthUnit<jps::Units::m>(quantity);
                break;
            case jps::Units::km:
                return jps::makeLengthUnit<jps::Units::km>(quantity);
                break;
            default:
                throw std::runtime_error(fmt::format(
                    FMT_STRING("Unit ({}) not yet implemented in python bindings."), unit));
        }
    }))
    // Read only parameters for getting the length unit quantity in desired unit
    .def_property_readonly(
        "um", &jps::LengthUnit::get<jps::Units::um>, "Retreive the quantity in micrometer")
    .def_property_readonly(
        "mm", &jps::LengthUnit::get<jps::Units::mm>, "Retreive the quantity in millimeter")
    .def_property_readonly(
        "cm", &jps::LengthUnit::get<jps::Units::cm>, "Retreive the quantity in centimeter")
    .def_property_readonly(
        "dm", &jps::LengthUnit::get<jps::Units::dm>, "Retreive the quantity in decimeter")
    .def_property_readonly(
        "m", &jps::LengthUnit::get<jps::Units::m>, "Retreive the quantity in meter")
    .def_property_readonly(
        "km", &jps::LengthUnit::get<jps::Units::km>, "Retreive the quantity in kilometer")
    // Comparison operators
    .def(pybind11::detail::self == pybind11::detail::self) // NOLINTLINE
    .def(pybind11::detail::self != pybind11::detail::self) // NOLINTLINE
    // magic function for string
    .def("__str__", [](const jps::LengthUnit & length_unit) {
        return fmt::format(FMT_STRING("{}"), length_unit);
    })
    .def("__repr__", [](const jps::LengthUnit & length_unit) {
        return fmt::format(FMT_STRING("{}"), length_unit);
    });
```

2021-03-18 08:13 UTC, schroedtert commented on cpp/pycore/source/geometry/length_unit_binding.cpp
> +                break;
Will be fixed in context of #56

2021-03-18 08:13 UTC, schroedtert approved these changes

2021-03-18 08:21 UTC, merged