Fix some minor typos in readme
JuPedSim/simulator pull request #54
Opened 2021-03-05 17:06 UTC by chraibi

Some typos  in README

2021-03-05 17:32 UTC, schroedtert requested changes

2021-03-05 17:32 UTC, schroedtert commented on README.md
> +To run *jps* jpscore's location needs to be in the `PYTHONPATH`, e.g.:
`jpscore.so` is not a type but the name of the library on unix systems

```suggestion
To run *jps* the location of the jpscore library (e.g., on Linux `jpscore.so`) needs to be in the `PYTHONPATH`, e.g.:
```

2021-03-05 17:35 UTC, schroedtert submitted a review, later dismissed

2021-03-08 14:26 UTC, JetteSchumann requested changes

2021-03-08 14:26 UTC, JetteSchumann commented on README.md
>  PYTHONPATH=~/simulation-build/bin ./jps/jps --help
```suggestion
PYTHONPATH=~/simulator-build/bin ./jps/jps --help
```

2021-03-08 14:26 UTC, JetteSchumann commented on README.md
>  initial setup, file handling etc.
Could you please correct line 108 as well?

2021-03-16 17:11 UTC, chraibi commented on README.md
>  initial setup, file handling etc.
Done!

2021-03-16 17:14 UTC, zeroset approved these changes
LGTM

2021-03-16 17:15 UTC, JetteSchumann approved these changes

2021-03-16 17:39 UTC, merged