Custom jpsexception
JuPedSim/simulator pull request #55
Opened 2021-03-11 13:33 UTC by schroedtert

Instead of using the default std exceptions, a custom exception is added (general purpose, and geometry specific).

2021-03-11 18:26 UTC, zeroset commented on cpp/libcore/source/util/jpsexception.cpp
> +// Created by tobias on 11.03.21.
Is there a reason for this? :)

2021-03-11 18:27 UTC, schroedtert commented on cpp/libcore/source/util/jpsexception.cpp
> +// Created by tobias on 11.03.21.
Not setting up your IDE properly ...

2021-03-16 12:03 UTC, zeroset requested changes

2021-03-16 12:03 UTC, zeroset commented on cpp/libcore/source/geometry/helper/polygon_helper.cpp
>      } catch(const std::runtime_error & e) {
Does `geometry::sortLineSegments` still throw `std::runtime_error`?

2021-03-18 14:54 UTC, schroedtert commented on cpp/libcore/source/geometry/helper/polygon_helper.cpp
>      } catch(const std::runtime_error & e) {
Nope, changed the catch block.

2021-03-18 14:55 UTC, schroedtert commented on cpp/pycore/source/jpscore_binding.cpp
> +    bind_jpsexception(m_util);
Not really, just used the same structure as in libcore part. Moved it to main module.

2021-03-18 14:55 UTC, schroedtert commented on cpp/libcore/source/util/jpsexception.cpp
> +// Created by tobias on 11.03.21.
Removed the file completely, as it was empty anyways

2021-03-23 10:31 UTC, zeroset approved these changes

2021-03-23 10:38 UTC, merged