Simulation workflow implementation
JuPedSim/simulator pull request #57
Opened 2021-03-18 13:38 UTC by zeroset

This PR is a draft of the simulation workflow.

2021-04-23 13:41 UTC, JetteSchumann commented
Notes on discussion with @schroedtert:
- merge #37 into #57 to create one PR for the basic simulation workflow
- we should discuss what is done in the simulation loop on python and c++ side. Maybe: python - loop over time, C++ - loop over agents
- simulation context must contain information about: agents, world, model parameters and model results
- next steps:
  - World Implementation and integration in simulation flow @JetteSchumann 
  - read in/create Agents and integrate in simulation flow @schroedtert

2021-05-27 08:51 UTC, schroedtert requested changes

2021-05-27 08:51 UTC, schroedtert commented on cpp/pycore/source/simulation_binding.cpp
> +        //} )
Please remove commented code and open Issue for the missing pybinds

2021-05-27 08:51 UTC, schroedtert commented on jps/jupedsim/util/simulation_files.py
> +            )
Do we need already test for this? And we should document somewhere, that one needs a `world.dxf` to start a simulation.

2021-05-28 07:44 UTC, zeroset commented on jps/jupedsim/util/simulation_files.py
> +            )
Thats just for the beginning. We can change the file name retrieval later.... I add this to a general Documentation Issue. #63

2021-05-28 08:49 UTC, schroedtert approved these changes

2021-05-28 08:58 UTC, merged