Parse unit information in dxf file
JuPedSim/simulator pull request #59
Opened 2021-03-18 15:44 UTC by JetteSchumann

The world parser is extended by reading in metadata stored in header variables of the dxf file. Units of the entities are checked. Only metric and decimal units that are defined in the `Units` enum are valid input formats. 

For a valid format, the data of the entities are parsed to geometry objects based on the corresponding LengthUnits.

2021-05-06 08:21 UTC, zeroset requested changes

2021-05-06 08:21 UTC, zeroset commented on jps/jupedsim/IO/worldparser.py
> +        if not WorldParser.checkMetricUnit(
Please split this check and throw different Exception Messages depending on the actual error.

2021-05-06 08:21 UTC, zeroset commented on jps/jupedsim/IO/worldparser.py
> +    def checkMetricUnit(doc: ezdxf.document.Drawing) -> bool:
I like these short function!

2021-05-06 12:29 UTC, schroedtert commented on jps/jupedsim/IO/worldparser.py
> +        For metric system decimal (14.4), fractional (14 2/5) and scientific format (1.4E+01) can be chosen, only decimal is supported
Just a question: Shouldn't the scientific format (1.4E+01) also work directly?

2021-05-26 14:22 UTC, JetteSchumann commented on jps/jupedsim/IO/worldparser.py
> +        if not WorldParser.checkMetricUnit(
Done

2021-05-26 14:26 UTC, JetteSchumann commented on jps/jupedsim/IO/worldparser.py
> +        For metric system decimal (14.4), fractional (14 2/5) and scientific format (1.4E+01) can be chosen, only decimal is supported
I am not sure about the actual meaning of this parameter anymore. Did some tests with QCAD and LibreCAD. DIMLUNIT did not change in the dxf file when using the scientific format. For LibreCAD the displayed position unit changed. So maybe it's only for defining the representation in the editor.

2021-05-27 06:26 UTC, zeroset commented on jps/jupedsim/tests/IO/test_worldparser.py
> +    def test_length_unit_incorrect(self, insunit):
i think the check for the raised exception in case of invalid decimal unit is missing.

2021-05-27 06:42 UTC, schroedtert commented on jps/jupedsim/IO/worldparser.py
> +        For metric system decimal (14.4), fractional (14 2/5) and scientific format (1.4E+01) can be chosen, only decimal is supported
Then is the question, do we need this check?

2021-05-27 06:44 UTC, JetteSchumann commented on jps/jupedsim/IO/worldparser.py
> +        For metric system decimal (14.4), fractional (14 2/5) and scientific format (1.4E+01) can be chosen, only decimal is supported
I decided to keep it as it might be important for other CAD editors. Can be changed later if we run into problems.

2021-05-27 11:46 UTC, JetteSchumann commented on jps/jupedsim/tests/IO/test_worldparser.py
> +    def test_length_unit_incorrect(self, insunit):
You are right. I added new tests.

2021-05-27 11:55 UTC, zeroset approved these changes

2021-05-27 12:05 UTC, merged