Add first simple trajectory writer
JuPedSim/simulator pull request #71
Opened 2021-06-05 08:46 UTC by schroedtert

- binding for agents
- interface for future trajectory writers
- simple trajectorywriter which writes: "frame agent_id x y z"

2021-06-07 14:24 UTC, schroedtert commented on cpp/pycore/source/simulation_binding.cpp
> +        .def_property_readonly("agents", &jps::Simulation::getAgents);
as reference

2021-06-08 06:24 UTC, Ozaq commented on cpp/libcore/source/agent/pedestrian.hpp
> +struct Pedestrian : public Identifiable<Pedestrian> {
It is probably better to use the `Identifiable` type as a field instead of a base class, aka. composition over inheritance. This leads in my experience to "easier to modify" code in the future, e.g. you do not have to deal with multiple inheritance or collections of "Identifiables"

2021-06-08 06:46 UTC, Ozaq commented on jps/jupedsim/IO/trajectorywriter.py
> +class TrajectoryWriter:
I see what you want to do here but this is where you can do things differently in python. This link https://realpython.com/python-interface/ is in my opinion a good first overview of the different variants on "how-to-do-interfaces" in python.

I think its worthwhile to discuss this in a smaller round either for this PR or after (since refactoring it now is easy) but we should establish some sort of "default" way to do python interfaces (and capture this in a README) for jps.

My 2 cents. :)

2021-06-17 09:15 UTC, schroedtert commented on cpp/libcore/source/agent/pedestrian.hpp
> +struct Pedestrian : public Identifiable<Pedestrian> {
Is solved via #73

2021-06-28 06:39 UTC, zeroset requested changes

2021-06-28 06:39 UTC, zeroset commented on jps/jupedsim/IO/trajectorywriter.py
> +    def write_header(trajectory_file: pathlib.Path):
```suggestion
    def write_header(trajectory_file: pathlib.Path) -> None:
```

2021-06-28 06:39 UTC, zeroset commented on jps/jupedsim/IO/trajectorywriter.py
> +    def write_trajectory(trajectory_file, step: int, agents: List[Agent]):
```suggestion
    def write_trajectory(trajectory_file, step: int, agents: List[Agent]) -> None:
```

2021-06-28 06:39 UTC, zeroset commented on jps/jupedsim/IO/trajectorywriter.py
> +    def write_header(trajectory_file: pathlib.Path):
```suggestion
    def write_header(trajectory_file: pathlib.Path) -> None:
```

2021-06-28 06:39 UTC, zeroset commented on jps/jupedsim/IO/trajectorywriter.py
> +    ):
```suggestion
    ) -> None:
```

2021-06-28 06:39 UTC, zeroset commented on cpp/pycore/source/util/unique_id_binding.cpp
> +        // NOLINTNEXTLINE(misc-redundant-expression)
:+1:

2021-07-05 07:12 UTC, schroedtert commented on jps/jupedsim/IO/trajectorywriter.py
> +    def write_trajectory(trajectory_file, step: int, agents: List[Agent]):
Added missing type hint (not via suggestion to get the formatting right)

2021-07-05 07:12 UTC, schroedtert commented on jps/jupedsim/IO/trajectorywriter.py
> +    def write_header(trajectory_file: pathlib.Path):
Added missing type hint

2021-07-05 07:12 UTC, schroedtert commented on jps/jupedsim/IO/trajectorywriter.py
> +    ):
Added missing type hint

2021-07-05 10:14 UTC, schroedtert commented on jps/jupedsim/IO/trajectorywriter.py
> +    def write_header(trajectory_file: pathlib.Path):
Added missing type hint (not via suggestion to get the formatting right)

2021-07-08 12:34 UTC, zeroset approved these changes

2021-07-08 12:39 UTC, merged