Adds LevelStorage to World
JuPedSim/simulator pull request #72
Opened 2021-06-09 09:03 UTC by zeroset

The World should store everything by Level. Level Storage contains the
geometry structure as well as the agents.

2021-07-08 07:47 UTC, JetteSchumann requested changes
We should discuss if we still need the Level. As it always comes with a LevelStorage it could be part of it. We wouldn't need the mapping Level - LevelStorage anymore and could just loop over the LevelStorages

2021-07-08 07:47 UTC, JetteSchumann commented on cpp/libcore/source/geometry/level_storage.hpp
> +    auto getAgents() const -> std::vector<Agent> const & { return m_agents; };
Maybe a const-cast is a better approach according to
https://stackoverflow.com/questions/123758/how-do-i-remove-code-duplication-between-similar-const-and-non-const-member-func/123995
(there's a comment on c++17)

2021-07-08 07:47 UTC, JetteSchumann commented on cpp/libcore/source/simulation.cpp
> +        }
I think the update needs to be done after results for all levels have been computed.
Think about movement between different levels in the future.

2021-07-08 07:47 UTC, JetteSchumann commented on cpp/libcore/source/geometry/world.hpp
> +    using LevelStorageContainer = std::unordered_map<Level, LevelStorage>;
Do we still need the Level? Could be part of LevelStorage

2021-07-08 07:47 UTC, JetteSchumann commented on cpp/libcore/source/geometry/world.hpp
> +    auto getLevels() const -> LevelStorageContainer const & { return m_level_to_level_storage; };
see prior comment regarding const_cast

2021-07-08 07:47 UTC, JetteSchumann commented on cpp/libcore/source/geometry/special_area.hpp
> +    auto operator=(const SpecialArea & p_other) -> SpecialArea & = default;
The comment states that it should not be copyable? Do we need it now?

2021-07-08 07:47 UTC, JetteSchumann commented on cpp/libcore/source/geometry/level.hpp
> +/// Hash required for unordered containers like unordered_map
We may not need the unordered map if the Level would be part of LevelStorage

2021-07-08 07:47 UTC, JetteSchumann commented on cpp/libcore/source/geometry/level.hpp
> +    }
I am confused :D

2021-07-08 07:47 UTC, JetteSchumann commented on cpp/libcore/source/geometry/level_storage.cpp
> +    m_agents.push_back({p_coordinate});
Do we need to check if the Agents/Areas/Lines have already been added?

2021-07-08 07:50 UTC, schroedtert commented on cpp/libcore/source/geometry/level_storage.hpp
> +    auto getAgents() const -> std::vector<Agent> const & { return m_agents; };
https://stackoverflow.com/a/47369227/9601068

2021-07-08 07:57 UTC, zeroset commented on cpp/libcore/source/geometry/world.hpp
> +    auto getLevels() const -> LevelStorageContainer const & { return m_level_to_level_storage; };
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-casts-const

2021-07-13 09:37 UTC, JetteSchumann commented on cpp/libcore/source/geometry/level_storage.cpp
> +    m_agents.push_back({p_coordinate});
Must be checked when parsing geometry or generating agents, but not here.

2021-07-13 09:39 UTC, JetteSchumann commented on cpp/libcore/source/geometry/world.hpp
> +    using LevelStorageContainer = std::unordered_map<Level, LevelStorage>;
We keep the map since accessing the levels is easier this way.

2021-07-22 13:39 UTC, JetteSchumann requested changes

2021-07-22 13:39 UTC, JetteSchumann commented on cpp/libcore/source/geometry/world.hpp
> +    auto addSpecialArea(Level const & p_level, SpecialArea const & p_area) -> void;
I think it's not consistent to add LineSegments and SpecialAreas via the World but not the Agents (those are added via the LevelStorage).
We should delete these functions and offer access via getLevelStorage() as used in the worldparser.

2021-07-23 07:00 UTC, schroedtert commented on cpp/libcore/source/geometry/world.hpp
> +    auto addSpecialArea(Level const & p_level, SpecialArea const & p_area) -> void;
Removed.

2021-07-23 07:06 UTC, JetteSchumann approved these changes

2021-08-02 10:00 UTC, merged