Refactor id tags
JuPedSim/simulator pull request #73
Opened 2021-06-11 09:14 UTC by Ozaq

So far is have been modelled with 'identifiable', the implementation was
changed to allow copy of ids and to prefer composition over inheritance.

The type 'Identifiable' has been renamed to 'UniqueId' to represent that
change, further the type has become formattable and can no longer be
converted to an integer. The idea here is that you should create
interfaces that rely on a specific id type for the "thing" you want to
identify. This way you cannot mix ids of different domains.

If there are external IDs that track the progress of, for example an
agent, you need to maintain a mapping from your external id to the id
generated by jpscore.

As part of this refactoring 'special_area' lost its external_id property
since this is not part of the domain of jpscore.

2021-06-15 05:44 UTC, zeroset requested changes

2021-06-15 05:44 UTC, zeroset commented on cpp/libcore/source/util/identifiable.hpp
>  #pragma once
Can you please rename the file to `unique_id.hpp`

2021-06-15 05:44 UTC, zeroset commented on cpp/libcore/source/util/identifiable.hpp
> +    Integer m_value{++uid_counter};
Why did you change to pre increment here?

2021-06-15 05:44 UTC, zeroset commented on cpp/libcore/test/util/test_identifiable.cpp
>  #include "util/identifiable.hpp"
Please rename the file to `test_unique_id.cpp`

2021-06-16 07:27 UTC, Ozaq commented on cpp/libcore/source/util/identifiable.hpp
>  #pragma once
done

2021-06-16 07:27 UTC, Ozaq commented on cpp/libcore/test/util/test_identifiable.cpp
>  #include "util/identifiable.hpp"
done

2021-06-16 07:54 UTC, Ozaq commented on cpp/libcore/source/util/identifiable.hpp
> +    Integer m_value{++uid_counter};
To keep `0` out of the valid (internal) ids. To have the possibility to express an invalid id, e.g. for testing

2021-06-16 14:53 UTC, zeroset approved these changes

2021-06-16 14:53 UTC, merged